import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Plus, Edit, Trash2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { useImageUpload } from '@/hooks/useImageUpload';
import ImageManager from './ImageManager';
import CategoryManagement from './CategoryManagement';
import CollectionManagement from './CollectionManagement';
import ProductVariationsTab from './ProductVariationsTab';

interface Product {
  id: string;
  name: string;
  description: string | null;
  collection_id: string | null;
  gross_weight: number | null;
  stone_weight: number | null;
  net_weight: number | null;
  carat: '22ct' | '18ct' | null;
  images: string[] | null;
  in_stock: boolean;
  price: number | null;
  created_at: string;
  updated_at: string;
  collections?: {
    name: string;
    categories?: {
      name: string;
    };
  };
}

interface Collection {
  id: string;
  name: string;
  category_id: string;
  categories?: {
    name: string;
  };
}

const ProductsManagement = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [collections, setCollections] = useState<Collection[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');
  const [currentImages, setCurrentImages] = useState<string[]>([]);
  const [newFiles, setNewFiles] = useState<FileList | null>(null);
  const [productVariations, setProductVariations] = useState<any[]>([]);
  const { toast } = useToast();
  const { uploadImage, deleteImage, isUploading } = useImageUpload();

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    collection_id: '',
    gross_weight: '',
    stone_weight: '',
    carat: '',
  });

  useEffect(() => {
    fetchProducts();
    fetchCollections();
  }, []);

  useEffect(() => {
    // Generate a new UUID when the form opens
    if (showAddForm && !editingProduct) {
      setAutoGeneratedId(crypto.randomUUID());
    }
  }, [showAddForm, editingProduct]);

  const fetchProducts = async () => {
    try {
      const { data, error } = await supabase
        .from('products')
        .select(`
          *,
          collections (
            name,
            categories (
              name
            )
          )
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      // Transform the data to ensure images is always a string array and handle type casting
      const transformedProducts = (data || []).map(product => ({
        ...product,
        images: Array.isArray(product.images) 
          ? product.images.map(img => String(img)) 
          : product.images 
            ? [String(product.images)]
            : []
      })) as Product[];
      
      setProducts(transformedProducts);
    } catch (error) {
      console.error('Error fetching products:', error);
      toast({
        title: "Error",
        description: "Failed to load products",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const fetchCollections = async () => {
    try {
      const { data, error } = await supabase
        .from('collections')
        .select(`
          id,
          name,
          category_id,
          categories (
            name
          )
        `)
        .order('name');

      if (error) throw error;
      setCollections(data || []);
    } catch (error) {
      console.error('Error fetching collections:', error);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      let finalImages: string[] = [];

      // Upload new files if any and get real URLs
      if (newFiles && newFiles.length > 0) {
        for (let i = 0; i < newFiles.length; i++) {
          const uploadedImage = await uploadImage(newFiles[i], 'products');
          if (uploadedImage) {
            finalImages.push(uploadedImage.url);
          }
        }
      }

      // Add existing images that are already uploaded (not blob URLs)
      const existingImages = currentImages.filter(img => !img.startsWith('blob:'));
      finalImages = [...existingImages, ...finalImages];
      
        const productData = {
        name: formData.name,
        description: formData.description || null,
        collection_id: formData.collection_id || null,
        gross_weight: formData.gross_weight ? parseFloat(formData.gross_weight) : null,
        stone_weight: formData.stone_weight ? parseFloat(formData.stone_weight) : null,
        carat: formData.carat as '22ct' | '18ct' | null || null,
        images: finalImages,
        in_stock: true,
        price: null,
      };

      if (editingProduct) {
        const { error } = await supabase
          .from('products')
          .update({ ...productData, updated_at: new Date().toISOString() })
          .eq('id', editingProduct.id);

        if (error) throw error;

        // Save product variations for existing products
        if (productVariations.length > 0) {
          // Get existing variations to determine which are new and which are updates
          const { data: existingVariations } = await supabase
            .from('product_variations')
            .select('id')
            .eq('parent_product_id', editingProduct.id);

          const existingIds = existingVariations?.map(v => v.id) || [];

          for (const variation of productVariations) {
            let variationImages: string[] = [];

            // Upload variation images
            if (variation.newFiles && variation.newFiles.length > 0) {
              for (let i = 0; i < variation.newFiles.length; i++) {
                const uploadedImage = await uploadImage(variation.newFiles[i], 'products');
                if (uploadedImage) {
                  variationImages.push(uploadedImage.url);
                }
              }
            }

            // Add existing variation images
            const existingVariationImages = variation.images.filter((img: string) => !img.startsWith('blob:'));
            variationImages = [...existingVariationImages, ...variationImages];

            const variationData = {
              parent_product_id: editingProduct.id,
              variation_name: variation.formData.variation_name || `Variation ${variation.id.slice(-8)}`,
              description: variation.formData.description || null,
              gross_weight: variation.formData.gross_weight ? parseFloat(variation.formData.gross_weight) : null,
              stone_weight: variation.formData.stone_weight ? parseFloat(variation.formData.stone_weight) : null,
              net_weight: variation.formData.gross_weight && variation.formData.stone_weight 
                ? parseFloat(variation.formData.gross_weight) - parseFloat(variation.formData.stone_weight)
                : parseFloat(variation.formData.gross_weight) || null,
              carat: variation.formData.carat || null,
              images: variationImages,
              in_stock: true,
              price: variation.formData.price ? parseFloat(variation.formData.price) : null,
            };

            // Check if this is an existing variation (has valid UUID and exists in DB) or new one
            const isExistingVariation = existingIds.includes(variation.id);

            if (isExistingVariation) {
              // Update existing variation
              const { error: updateError } = await supabase
                .from('product_variations')
                .update(variationData)
                .eq('id', variation.id);

              if (updateError) throw updateError;
            } else {
              // Insert new variation
              const { error: insertError } = await supabase
                .from('product_variations')
                .insert([variationData]);

              if (insertError) throw insertError;
            }
          }

          // Delete variations that were removed from the form
          const currentVariationIds = productVariations.map(v => v.id);
          const variationsToDelete = existingIds.filter(id => !currentVariationIds.includes(id));
          
          if (variationsToDelete.length > 0) {
            await supabase
              .from('product_variations')
              .delete()
              .in('id', variationsToDelete);
          }
        }
        
        toast({
          title: "Success",
          description: "Product and variations updated successfully",
        });
      } else {
        // For new products, let Supabase generate the ID
        const { data: insertedProduct, error } = await supabase
          .from('products')
          .insert([productData])
          .select('id')
          .single();

        if (error) throw error;

        // Save product variations if any
        if (productVariations.length > 0) {
          const actualProductId = insertedProduct?.id || autoGeneratedId;
          
          for (const variation of productVariations) {
            let variationImages: string[] = [];

            // Upload variation images
            if (variation.newFiles && variation.newFiles.length > 0) {
              for (let i = 0; i < variation.newFiles.length; i++) {
                const uploadedImage = await uploadImage(variation.newFiles[i], 'products');
                if (uploadedImage) {
                  variationImages.push(uploadedImage.url);
                }
              }
            }

            // Add existing variation images
            const existingVariationImages = variation.images.filter((img: string) => !img.startsWith('blob:'));
            variationImages = [...existingVariationImages, ...variationImages];

            const variationData = {
              parent_product_id: actualProductId,
              variation_name: variation.formData.variation_name || `Variation ${variation.id.slice(-8)}`,
              description: variation.formData.description || null,
              gross_weight: variation.formData.gross_weight ? parseFloat(variation.formData.gross_weight) : null,
              stone_weight: variation.formData.stone_weight ? parseFloat(variation.formData.stone_weight) : null,
              net_weight: variation.formData.gross_weight && variation.formData.stone_weight 
                ? parseFloat(variation.formData.gross_weight) - parseFloat(variation.formData.stone_weight)
                : parseFloat(variation.formData.gross_weight) || null,
              carat: variation.formData.carat || null,
              images: variationImages,
              in_stock: true,
              price: variation.formData.price ? parseFloat(variation.formData.price) : null,
            };

            const { error: variationError } = await supabase
              .from('product_variations')
              .insert([variationData]);

            if (variationError) throw variationError;
          }
        }

        toast({
          title: "Success",
          description: "Product and variations added successfully",
        });
      }

      resetForm();
      fetchProducts(); // Refresh the products list
    } catch (error) {
      console.error('Error saving product:', error);
      toast({
        title: "Error",
        description: "Failed to save product",
        variant: "destructive",
      });
    }
  };

  const handleEdit = async (product: Product) => {
    setEditingProduct(product);
    setFormData({
      name: product.name,
      description: product.description || '',
      collection_id: product.collection_id || '',
      gross_weight: product.gross_weight?.toString() || '',
      stone_weight: product.stone_weight?.toString() || '',
      carat: product.carat || '',
    });
    setCurrentImages(product.images || []);
    setNewFiles(null);

    // Fetch existing variations for this product
    try {
      const { data: existingVariations, error } = await supabase
        .from('product_variations')
        .select('*')
        .eq('parent_product_id', product.id);

      if (error) throw error;

      if (existingVariations && existingVariations.length > 0) {
        // Convert database variations to the format expected by ProductVariationsTab
        const formattedVariations = existingVariations.map(variation => ({
          id: variation.id,
          formData: {
            variation_name: variation.variation_name,
            description: variation.description,
            gross_weight: variation.gross_weight?.toString(),
            stone_weight: variation.stone_weight?.toString(),
            carat: variation.carat,
            price: variation.price?.toString(),
          },
          images: Array.isArray(variation.images) ? variation.images : [],
          newFiles: null,
        }));
        setProductVariations(formattedVariations);
      } else {
        // Reset to empty if no variations found
        setProductVariations([]);
      }
    } catch (error) {
      console.error('Error fetching variations:', error);
      setProductVariations([]);
    }

    setShowAddForm(true);
  };

  const handleDelete = async (productId: string) => {
    try {
      const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', productId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Product deleted successfully",
      });
      
      fetchProducts(); // Refresh the products list
    } catch (error) {
      console.error('Error deleting product:', error);
      toast({
        title: "Error",
        description: "Failed to delete product",
        variant: "destructive",
      });
    }
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      collection_id: '',
      gross_weight: '',
      stone_weight: '',
      carat: '',
    });
    
    // Clean up any blob URLs
    currentImages.forEach(img => {
      if (img.startsWith('blob:')) {
        URL.revokeObjectURL(img);
      }
    });
    
    setCurrentImages([]);
    setNewFiles(null);
    setShowAddForm(false);
    setEditingProduct(null);
    setAutoGeneratedId('');
    setProductVariations([]);
  };

  const handleFileChange = (files: FileList) => {
    setNewFiles(files);
  };

  const handleImagesChange = async (images: string[]) => {
    // Find removed images and clean up blob URLs
    const removedImages = currentImages.filter(img => !images.includes(img));
    
    for (const removedImage of removedImages) {
      if (removedImage.startsWith('blob:')) {
        URL.revokeObjectURL(removedImage);
      } else {
        // Delete actual uploaded images from storage
        const imagePath = removedImage.split('/').pop();
        if (imagePath) {
          await deleteImage(`products/${imagePath}`);
        }
      }
    }
    
    setCurrentImages(images);
  };

  // Calculate net weight
  const netWeight = formData.gross_weight && formData.stone_weight 
    ? (parseFloat(formData.gross_weight) - parseFloat(formData.stone_weight)).toFixed(3)
    : formData.gross_weight || '';

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Products Management</h2>
          <p className="text-muted-foreground">Loading products...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Products Management</h2>
          <p className="text-muted-foreground">
            Manage your jewelry inventory
          </p>
        </div>
        <Button onClick={() => setShowAddForm(true)}>
          <Plus className="h-4 w-4 mr-2" />
          Add Product
        </Button>
      </div>

      <Dialog open={showAddForm} onOpenChange={setShowAddForm}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingProduct ? 'Edit Product' : 'Add New Product'}</DialogTitle>
            <DialogDescription>
              {editingProduct ? 'Update product information' : 'Fill in the details to add a new product'}
            </DialogDescription>
          </DialogHeader>
          
          <form onSubmit={handleSubmit}>
            <Tabs defaultValue="main" className="w-full">
              <TabsList className={`grid w-full ${editingProduct ? 'grid-cols-2' : 'grid-cols-1'}`}>
                <TabsTrigger value="main">Main Product</TabsTrigger>
                {editingProduct && <TabsTrigger value="variations">Variations</TabsTrigger>}
              </TabsList>
              
              <TabsContent value="main" className="space-y-4 mt-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="product-id">Product ID</Label>
                    <Input
                      id="product-id"
                      value={editingProduct?.id || autoGeneratedId}
                      disabled
                      className="bg-muted"
                    />
                  </div>
                  <div>
                    <Label htmlFor="name">Product Name</Label>
                    <Input
                      id="name"
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="collection">Collection</Label>
                    <Select
                      value={formData.collection_id}
                      onValueChange={(value) => setFormData({ ...formData, collection_id: value })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select collection" />
                      </SelectTrigger>
                      <SelectContent>
                        {collections.map((collection) => (
                          <SelectItem key={collection.id} value={collection.id}>
                            {collection.name} ({collection.categories?.name})
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="gross_weight">Gross Weight (g)</Label>
                    <Input
                      id="gross_weight"
                      type="number"
                      step="0.001"
                      value={formData.gross_weight}
                      onChange={(e) => setFormData({ ...formData, gross_weight: e.target.value })}
                      placeholder="0.000"
                    />
                  </div>
                  <div>
                    <Label htmlFor="stone_weight">Stone Weight (g)</Label>
                    <Input
                      id="stone_weight"
                      type="number"
                      step="0.001"
                      value={formData.stone_weight}
                      onChange={(e) => setFormData({ ...formData, stone_weight: e.target.value })}
                      placeholder="0.000"
                    />
                  </div>
                  <div>
                    <Label htmlFor="net_weight">Net Weight (g)</Label>
                    <Input
                      id="net_weight"
                      value={netWeight}
                      disabled
                      className="bg-muted"
                      placeholder="Auto-calculated"
                    />
                  </div>
                  <div>
                    <Label htmlFor="carat">Carat</Label>
                    <Select
                      value={formData.carat}
                      onValueChange={(value) => setFormData({ ...formData, carat: value })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select carat" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="22ct">22ct</SelectItem>
                        <SelectItem value="18ct">18ct</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label htmlFor="description">Description</Label>
                  <Textarea
                    id="description"
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    placeholder="Product description..."
                  />
                </div>
                
                <ImageManager
                  images={currentImages}
                  onImagesChange={handleImagesChange}
                  onFileChange={handleFileChange}
                  isLoading={isLoading || isUploading}
                  label="Product Images"
                  multiple={true}
                />
              </TabsContent>
              
              {editingProduct && (
                <TabsContent value="variations" className="mt-6">
                  <ProductVariationsTab
                    parentProductId={editingProduct.id}
                    collections={collections}
                    isUploading={isUploading}
                    onVariationsChange={setProductVariations}
                    initialVariations={productVariations}
                  />
                </TabsContent>
              )}
            </Tabs>
            
            {/* Action buttons moved to bottom for both tabs */}
            <div className="flex space-x-2 mt-6 pt-4 border-t">
              <Button type="submit" disabled={isLoading || isUploading}>
                {editingProduct ? 'Update Product' : 'Add Product'}
              </Button>
              <Button type="button" variant="outline" onClick={resetForm}>
                Cancel
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <Card>
        <CardHeader>
          <CardTitle>Products ({products.length})</CardTitle>
          <CardDescription>
            Manage your jewelry inventory
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Product ID</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Collection</TableHead>
                <TableHead>Category</TableHead>
                <TableHead>Gross Weight</TableHead>
                <TableHead>Carat</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {products.map((product) => (
                <TableRow key={product.id}>
                  <TableCell className="font-mono text-xs">{product.id.slice(0, 8)}...</TableCell>
                  <TableCell className="font-medium">{product.name}</TableCell>
                  <TableCell>{product.collections?.name || '-'}</TableCell>
                  <TableCell>{product.collections?.categories?.name || '-'}</TableCell>
                  <TableCell>
                    {product.gross_weight ? parseFloat(product.gross_weight.toString()).toFixed(3) : '-'}
                  </TableCell>
                  <TableCell>{product.carat || '-'}</TableCell>
                  <TableCell>
                    <div className="flex space-x-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleEdit(product)}
                        className="bg-blue-50 hover:bg-blue-100 border-blue-200"
                      >
                        <Edit className="h-4 w-4" />
                      </Button>
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button
                            size="sm"
                            variant="outline"
                            className="bg-red-50 hover:bg-red-100 border-red-200"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                            <AlertDialogDescription>
                              This action cannot be undone. This will permanently delete the product
                              "{product.name}" from your inventory.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => handleDelete(product.id)}
                              className="bg-red-600 hover:bg-red-700"
                            >
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {products.length === 0 && (
                <TableRow>
                  <TableCell colSpan={7} className="text-center text-muted-foreground">
                    No products found. Add your first product to get started.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default ProductsManagement;
