import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Plus, Edit, Trash2, Layers } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { useImageUpload } from '@/hooks/useImageUpload';
import ImageManager from './ImageManager';
import CategoryManagement from './CategoryManagement';
import CollectionManagement from './CollectionManagement';

interface Product {
  id: string;
  name: string;
  description: string | null;
  collection_id: string | null;
  gross_weight: number | null;
  stone_weight: number | null;
  net_weight: number | null;
  carat: '22ct' | '18ct' | null;
  images: string[] | null;
  in_stock: boolean;
  price: number | null;
  created_at: string;
  updated_at: string;
  collections?: {
    name: string;
    categories?: {
      name: string;
    };
  };
}

interface ProductVariation {
  id: string;
  parent_product_id: string;
  variation_name: string;
  description: string | null;
  gross_weight: number | null;
  stone_weight: number | null;
  net_weight: number | null;
  carat: '22ct' | '18ct' | null;
  images: string[] | null;
  in_stock: boolean;
  price: number | null;
  created_at: string;
  updated_at: string;
}

interface Collection {
  id: string;
  name: string;
  category_id: string;
  categories?: {
    name: string;
  };
}

const ProductsManagement = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [collections, setCollections] = useState<Collection[]>([]);
  const [variations, setVariations] = useState<ProductVariation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [selectedProductForVariation, setSelectedProductForVariation] = useState<Product | null>(null);
  const [showVariationForm, setShowVariationForm] = useState(false);
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');
  const [currentImages, setCurrentImages] = useState<string[]>([]);
  const [newFiles, setNewFiles] = useState<FileList | null>(null);
  const [activeTab, setActiveTab] = useState<string>('product');
  const [editingVariation, setEditingVariation] = useState<ProductVariation | null>(null);
  const { toast } = useToast();
  const { uploadImage, deleteImage, isUploading } = useImageUpload();

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    collection_id: '',
    gross_weight: '',
    stone_weight: '',
    carat: '',
  });

  const [variationFormData, setVariationFormData] = useState({
    variation_name: '',
    description: '',
    gross_weight: '',
    stone_weight: '',
    carat: '',
  });

  useEffect(() => {
    fetchProducts();
    fetchCollections();
  }, []);

  useEffect(() => {
    // Generate a new UUID when any form opens
    if ((showAddForm && !editingProduct) || showVariationForm) {
      setAutoGeneratedId(crypto.randomUUID());
    }
  }, [showAddForm, editingProduct, showVariationForm]);

  const fetchProducts = async () => {
    try {
      const { data, error } = await supabase
        .from('products')
        .select(`
          *,
          collections (
            name,
            categories (
              name
            )
          )
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      const transformedProducts = (data || []).map(product => ({
        ...product,
        images: Array.isArray(product.images) 
          ? product.images.map(img => String(img)) 
          : product.images 
            ? [String(product.images)]
            : []
      })) as Product[];
      
      setProducts(transformedProducts);
    } catch (error) {
      console.error('Error fetching products:', error);
      toast({
        title: "Error",
        description: "Failed to load products",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const fetchCollections = async () => {
    try {
      const { data, error } = await supabase
        .from('collections')
        .select(`
          id,
          name,
          category_id,
          categories (
            name
          )
        `)
        .order('name');

      if (error) throw error;
      setCollections(data || []);
    } catch (error) {
      console.error('Error fetching collections:', error);
    }
  };

  const fetchVariations = async (productId: string) => {
    try {
      const { data, error } = await supabase
        .from('product_variations')
        .select('*')
        .eq('parent_product_id', productId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      const transformedVariations = (data || []).map(variation => ({
        ...variation,
        images: Array.isArray(variation.images) 
          ? variation.images.map(img => String(img)) 
          : variation.images 
            ? [String(variation.images)]
            : []
      })) as ProductVariation[];
      
      setVariations(transformedVariations);
      return transformedVariations;
    } catch (error) {
      console.error('Error fetching variations:', error);
      return [];
    }
  };

  const handleAddVariation = async (product: Product) => {
    const productVariations = await fetchVariations(product.id);
    
    if (productVariations.length >= 20) {
      toast({
        title: "Maximum Variations Reached",
        description: "A product can only have up to 20 variations.",
        variant: "destructive",
      });
      return;
    }
    
    setSelectedProductForVariation(product);
    setVariationFormData({
      variation_name: '',
      description: '',
      gross_weight: '',
      stone_weight: '',
      carat: '',
    });
    setCurrentImages([]);
    setNewFiles(null);
    setEditingVariation(null);
    setShowVariationForm(true);
  };

  const handleEditVariation = (variation: ProductVariation) => {
    setEditingVariation(variation);
    setVariationFormData({
      variation_name: variation.variation_name,
      description: variation.description || '',
      gross_weight: variation.gross_weight?.toString() || '',
      stone_weight: variation.stone_weight?.toString() || '',
      carat: variation.carat || '',
    });
    setCurrentImages(variation.images || []);
    setNewFiles(null);
    setShowVariationForm(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      let finalImages: string[] = [];

      if (newFiles && newFiles.length > 0) {
        for (let i = 0; i < newFiles.length; i++) {
          const uploadedImage = await uploadImage(newFiles[i], 'products');
          if (uploadedImage) {
            finalImages.push(uploadedImage.url);
          }
        }
      }

      const existingImages = currentImages.filter(img => !img.startsWith('blob:'));
      finalImages = [...existingImages, ...finalImages];
      
      const productData = {
        id: editingProduct ? editingProduct.id : autoGeneratedId,
        name: formData.name,
        description: formData.description || null,
        collection_id: formData.collection_id || null,
        gross_weight: formData.gross_weight ? parseFloat(formData.gross_weight) : null,
        stone_weight: formData.stone_weight ? parseFloat(formData.stone_weight) : null,
        carat: formData.carat as '22ct' | '18ct' | null || null,
        images: finalImages,
        in_stock: true,
        price: null,
      };

      if (editingProduct) {
        const { error } = await supabase
          .from('products')
          .update({ ...productData, updated_at: new Date().toISOString() })
          .eq('id', editingProduct.id);

        if (error) throw error;
        
        toast({
          title: "Success",
          description: "Product updated successfully",
        });
      } else {
        const { error } = await supabase
          .from('products')
          .insert([productData]);

        if (error) throw error;

        toast({
          title: "Success",
          description: "Product created successfully",
        });
      }

      resetForm();
      fetchProducts();
    } catch (error) {
      console.error('Error saving product:', error);
      toast({
        title: "Error",
        description: "Failed to save product",
        variant: "destructive",
      });
    }
  };

  const handleVariationSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!selectedProductForVariation && !editingVariation) return;
    
    try {
      let finalImages: string[] = [];

      if (newFiles && newFiles.length > 0) {
        for (let i = 0; i < newFiles.length; i++) {
          const uploadedImage = await uploadImage(newFiles[i], 'products');
          if (uploadedImage) {
            finalImages.push(uploadedImage.url);
          }
        }
      }

      const existingImages = currentImages.filter(img => !img.startsWith('blob:'));
      finalImages = [...existingImages, ...finalImages];
      
      const variationData = {
        variation_name: variationFormData.variation_name,
        description: variationFormData.description || null,
        gross_weight: variationFormData.gross_weight ? parseFloat(variationFormData.gross_weight) : null,
        stone_weight: variationFormData.stone_weight ? parseFloat(variationFormData.stone_weight) : null,
        carat: variationFormData.carat as '22ct' | '18ct' | null || null,
        images: finalImages,
        in_stock: true,
        price: null,
      };

      if (editingVariation) {
        const { error } = await supabase
          .from('product_variations')
          .update({ ...variationData, updated_at: new Date().toISOString() })
          .eq('id', editingVariation.id);

        if (error) throw error;

        toast({
          title: "Success",
          description: "Variation updated successfully",
        });
      } else {
        const fullVariationData = {
          id: autoGeneratedId,
          parent_product_id: selectedProductForVariation!.id,
          ...variationData,
        };

        const { error } = await supabase
          .from('product_variations')
          .insert([fullVariationData]);

        if (error) throw error;

        toast({
          title: "Success",
          description: "Variation created successfully",
        });
      }

      resetVariationForm();
      fetchProducts();
    } catch (error) {
      console.error('Error saving variation:', error);
      toast({
        title: "Error",
        description: "Failed to save variation",
        variant: "destructive",
      });
    }
  };

  const handleEdit = async (product: Product) => {
    setEditingProduct(product);
    setFormData({
      name: product.name,
      description: product.description || '',
      collection_id: product.collection_id || '',
      gross_weight: product.gross_weight?.toString() || '',
      stone_weight: product.stone_weight?.toString() || '',
      carat: product.carat || '',
    });
    setCurrentImages(product.images || []);
    setNewFiles(null);
    
    // Fetch variations for this product
    await fetchVariations(product.id);
    setActiveTab('product');
    setShowAddForm(true);
  };

  const handleDelete = async (productId: string) => {
    try {
      const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', productId);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Product deleted successfully",
      });
      
      fetchProducts();
    } catch (error) {
      console.error('Error deleting product:', error);
      toast({
        title: "Error",
        description: "Failed to delete product",
        variant: "destructive",
      });
    }
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      collection_id: '',
      gross_weight: '',
      stone_weight: '',
      carat: '',
    });
    
    currentImages.forEach(img => {
      if (img.startsWith('blob:')) {
        URL.revokeObjectURL(img);
      }
    });
    
    setCurrentImages([]);
    setNewFiles(null);
    setShowAddForm(false);
    setEditingProduct(null);
    setAutoGeneratedId('');
    setVariations([]);
    setActiveTab('product');
  };

  const resetVariationForm = () => {
    setVariationFormData({
      variation_name: '',
      description: '',
      gross_weight: '',
      stone_weight: '',
      carat: '',
    });
    
    currentImages.forEach(img => {
      if (img.startsWith('blob:')) {
        URL.revokeObjectURL(img);
      }
    });
    
    setCurrentImages([]);
    setNewFiles(null);
    setShowVariationForm(false);
    setSelectedProductForVariation(null);
    setEditingVariation(null);
    setAutoGeneratedId('');
  };

  const handleFileChange = (files: FileList) => {
    setNewFiles(files);
  };

  const handleImagesChange = async (images: string[]) => {
    const removedImages = currentImages.filter(img => !images.includes(img));
    
    for (const removedImage of removedImages) {
      if (removedImage.startsWith('blob:')) {
        URL.revokeObjectURL(removedImage);
      } else {
        const imagePath = removedImage.split('/').pop();
        if (imagePath) {
          await deleteImage(`products/${imagePath}`);
        }
      }
    }
    
    setCurrentImages(images);
  };

  // Calculate net weight for product
  const netWeight = formData.gross_weight && formData.stone_weight 
    ? (parseFloat(formData.gross_weight) - parseFloat(formData.stone_weight)).toFixed(3)
    : formData.gross_weight || '';

  // Calculate net weight for variation
  const variationNetWeight = variationFormData.gross_weight && variationFormData.stone_weight 
    ? (parseFloat(variationFormData.gross_weight) - parseFloat(variationFormData.stone_weight)).toFixed(3)
    : variationFormData.gross_weight || '';

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Products Management</h2>
          <p className="text-muted-foreground">Loading products...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Products Management</h2>
          <p className="text-muted-foreground">
            Manage your jewelry inventory
          </p>
        </div>
        <Button onClick={() => setShowAddForm(true)}>
          <Plus className="h-4 w-4 mr-2" />
          Add Product
        </Button>
      </div>

      {/* Main Product Form Modal */}
      <Dialog open={showAddForm} onOpenChange={setShowAddForm}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingProduct ? 'Edit Product' : 'New Product'}</DialogTitle>
            <DialogDescription>
              {editingProduct ? 'Update product information and manage variations' : 'Fill in the details to create a new product'}
            </DialogDescription>
          </DialogHeader>

          {editingProduct ? (
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="product">{editingProduct.name}</TabsTrigger>
                <TabsTrigger value="variations">Variations</TabsTrigger>
              </TabsList>

              <TabsContent value="product">
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="product-id">Product ID</Label>
                      <Input
                        id="product-id"
                        value={editingProduct?.id || autoGeneratedId}
                        disabled
                        className="bg-muted"
                      />
                    </div>
                    <div>
                      <Label htmlFor="name">Product Name</Label>
                      <Input
                        id="name"
                        value={formData.name}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        required
                      />
                    </div>
                    <div>
                      <Label htmlFor="collection">Collection</Label>
                      <Select
                        value={formData.collection_id}
                        onValueChange={(value) => setFormData({ ...formData, collection_id: value })}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select collection" />
                        </SelectTrigger>
                        <SelectContent>
                          {collections.map((collection) => (
                            <SelectItem key={collection.id} value={collection.id}>
                              {collection.name} ({collection.categories?.name})
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label htmlFor="gross_weight">Gross Weight (g)</Label>
                      <Input
                        id="gross_weight"
                        type="number"
                        step="0.001"
                        value={formData.gross_weight}
                        onChange={(e) => setFormData({ ...formData, gross_weight: e.target.value })}
                        placeholder="0.000"
                      />
                    </div>
                    <div>
                      <Label htmlFor="stone_weight">Stone Weight (g)</Label>
                      <Input
                        id="stone_weight"
                        type="number"
                        step="0.001"
                        value={formData.stone_weight}
                        onChange={(e) => setFormData({ ...formData, stone_weight: e.target.value })}
                        placeholder="0.000"
                      />
                    </div>
                    <div>
                      <Label htmlFor="net_weight">Net Weight (g)</Label>
                      <Input
                        id="net_weight"
                        value={netWeight}
                        disabled
                        className="bg-muted"
                        placeholder="Auto-calculated"
                      />
                    </div>
                    <div>
                      <Label htmlFor="carat">Carat</Label>
                      <Select
                        value={formData.carat}
                        onValueChange={(value) => setFormData({ ...formData, carat: value })}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select carat" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="22ct">22ct</SelectItem>
                          <SelectItem value="18ct">18ct</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div>
                    <Label htmlFor="description">Description</Label>
                    <Textarea
                      id="description"
                      value={formData.description}
                      onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                      placeholder="Product description..."
                    />
                  </div>
                  
                  <ImageManager
                    images={currentImages}
                    onImagesChange={handleImagesChange}
                    onFileChange={handleFileChange}
                    isLoading={isLoading || isUploading}
                    label="Product Images"
                    multiple={true}
                  />
                  
                  <div className="flex space-x-2">
                    <Button type="submit" disabled={isLoading || isUploading}>
                      Update Product
                    </Button>
                    <Button type="button" variant="outline" onClick={resetForm}>
                      Cancel
                    </Button>
                  </div>
                </form>
              </TabsContent>

              <TabsContent value="variations">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-medium">Product Variations</h3>
                  </div>
                  
                  {variations.length > 0 ? (
                    <div className="space-y-2">
                      {variations.map((variation) => (
                        <div key={variation.id} className="border rounded p-3">
                          <div className="flex items-center justify-between">
                            <div>
                              <h4 className="font-medium">{variation.variation_name}</h4>
                              <p className="text-sm text-muted-foreground">
                                Gross: {variation.gross_weight}g | Carat: {variation.carat}
                              </p>
                            </div>
                            <div className="flex space-x-2">
                              <Button 
                                size="sm" 
                                variant="outline"
                                onClick={() => handleEditVariation(variation)}
                              >
                                <Edit className="h-4 w-4" />
                              </Button>
                              <Button size="sm" variant="outline" className="text-red-600">
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-muted-foreground text-center py-8">
                      No variations found. Create your first variation for this product.
                    </p>
                  )}
                </div>
              </TabsContent>
            </Tabs>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="product-id">Product ID</Label>
                  <Input
                    id="product-id"
                    value={editingProduct?.id || autoGeneratedId}
                    disabled
                    className="bg-muted"
                  />
                </div>
                <div>
                  <Label htmlFor="name">Product Name</Label>
                  <Input
                    id="name"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="collection">Collection</Label>
                  <Select
                    value={formData.collection_id}
                    onValueChange={(value) => setFormData({ ...formData, collection_id: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select collection" />
                    </SelectTrigger>
                    <SelectContent>
                      {collections.map((collection) => (
                        <SelectItem key={collection.id} value={collection.id}>
                          {collection.name} ({collection.categories?.name})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="gross_weight">Gross Weight (g)</Label>
                  <Input
                    id="gross_weight"
                    type="number"
                    step="0.001"
                    value={formData.gross_weight}
                    onChange={(e) => setFormData({ ...formData, gross_weight: e.target.value })}
                    placeholder="0.000"
                  />
                </div>
                <div>
                  <Label htmlFor="stone_weight">Stone Weight (g)</Label>
                  <Input
                    id="stone_weight"
                    type="number"
                    step="0.001"
                    value={formData.stone_weight}
                    onChange={(e) => setFormData({ ...formData, stone_weight: e.target.value })}
                    placeholder="0.000"
                  />
                </div>
                <div>
                  <Label htmlFor="net_weight">Net Weight (g)</Label>
                  <Input
                    id="net_weight"
                    value={netWeight}
                    disabled
                    className="bg-muted"
                    placeholder="Auto-calculated"
                  />
                </div>
                <div>
                  <Label htmlFor="carat">Carat</Label>
                  <Select
                    value={formData.carat}
                    onValueChange={(value) => setFormData({ ...formData, carat: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select carat" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="22ct">22ct</SelectItem>
                      <SelectItem value="18ct">18ct</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div>
                <Label htmlFor="description">Description</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Product description..."
                />
              </div>
              
              <ImageManager
                images={currentImages}
                onImagesChange={handleImagesChange}
                onFileChange={handleFileChange}
                isLoading={isLoading || isUploading}
                label="Product Images"
                multiple={true}
              />
              
              <div className="flex space-x-2">
                <Button type="submit" disabled={isLoading || isUploading}>
                  Create Product
                </Button>
                <Button type="button" variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </div>
            </form>
          )}
        </DialogContent>
      </Dialog>

      {/* Variation Form Modal */}
      <Dialog open={showVariationForm} onOpenChange={setShowVariationForm}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {editingVariation ? 'Edit Variation' : 'New Variation'}
            </DialogTitle>
            <DialogDescription>
              {editingVariation 
                ? `Update variation details for ${editingVariation.variation_name}`
                : `Create a new variation for ${selectedProductForVariation?.name}`
              }
            </DialogDescription>
          </DialogHeader>
          <form onSubmit={handleVariationSubmit} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label htmlFor="variation-id">Variation ID</Label>
                <Input
                  id="variation-id"
                  value={editingVariation?.id || autoGeneratedId}
                  disabled
                  className="bg-muted"
                />
              </div>
              <div>
                <Label htmlFor="variation_name">Variation Name</Label>
                <Input
                  id="variation_name"
                  value={variationFormData.variation_name}
                  onChange={(e) => setVariationFormData({ ...variationFormData, variation_name: e.target.value })}
                  required
                />
              </div>
              <div>
                <Label htmlFor="variation_gross_weight">Gross Weight (g)</Label>
                <Input
                  id="variation_gross_weight"
                  type="number"
                  step="0.001"
                  value={variationFormData.gross_weight}
                  onChange={(e) => setVariationFormData({ ...variationFormData, gross_weight: e.target.value })}
                  placeholder="0.000"
                />
              </div>
              <div>
                <Label htmlFor="variation_stone_weight">Stone Weight (g)</Label>
                <Input
                  id="variation_stone_weight"
                  type="number"
                  step="0.001"
                  value={variationFormData.stone_weight}
                  onChange={(e) => setVariationFormData({ ...variationFormData, stone_weight: e.target.value })}
                  placeholder="0.000"
                />
              </div>
              <div>
                <Label htmlFor="variation_net_weight">Net Weight (g)</Label>
                <Input
                  id="variation_net_weight"
                  value={variationNetWeight}
                  disabled
                  className="bg-muted"
                  placeholder="Auto-calculated"
                />
              </div>
              <div>
                <Label htmlFor="variation_carat">Carat</Label>
                <Select
                  value={variationFormData.carat}
                  onValueChange={(value) => setVariationFormData({ ...variationFormData, carat: value })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select carat" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="22ct">22ct</SelectItem>
                    <SelectItem value="18ct">18ct</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div>
              <Label htmlFor="variation_description">Description</Label>
              <Textarea
                id="variation_description"
                value={variationFormData.description}
                onChange={(e) => setVariationFormData({ ...variationFormData, description: e.target.value })}
                placeholder="Variation description..."
              />
            </div>
            
            <ImageManager
              images={currentImages}
              onImagesChange={handleImagesChange}
              onFileChange={handleFileChange}
              isLoading={isLoading || isUploading}
              label="Variation Images"
              multiple={true}
            />
            
            <div className="flex space-x-2">
              <Button type="submit" disabled={isLoading || isUploading}>
                {editingVariation ? 'Update Variation' : 'Save'}
              </Button>
              <Button type="button" variant="outline" onClick={resetVariationForm}>
                Cancel
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <Card>
        <CardHeader>
          <CardTitle>Products ({products.length})</CardTitle>
          <CardDescription>
            Manage your jewelry inventory
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Product ID</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Collection</TableHead>
                <TableHead>Category</TableHead>
                <TableHead>Gross Weight</TableHead>
                <TableHead>Carat</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {products.map((product) => (
                <TableRow key={product.id}>
                  <TableCell className="font-mono text-xs">{product.id.slice(0, 8)}...</TableCell>
                  <TableCell className="font-medium">{product.name}</TableCell>
                  <TableCell>{product.collections?.name || '-'}</TableCell>
                  <TableCell>{product.collections?.categories?.name || '-'}</TableCell>
                  <TableCell>
                    {product.gross_weight ? parseFloat(product.gross_weight.toString()).toFixed(3) : '-'}
                  </TableCell>
                  <TableCell>{product.carat || '-'}</TableCell>
                  <TableCell>
                    <div className="flex space-x-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleAddVariation(product)}
                        className="bg-green-50 hover:bg-green-100 border-green-200"
                        title="Add Variation"
                      >
                        <Layers className="h-4 w-4" />
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handleEdit(product)}
                        className="bg-blue-50 hover:bg-blue-100 border-blue-200"
                      >
                        <Edit className="h-4 w-4" />
                      </Button>
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button
                            size="sm"
                            variant="outline"
                            className="bg-red-50 hover:bg-red-100 border-red-200"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                            <AlertDialogDescription>
                              This action cannot be undone. This will permanently delete the product
                              "{product.name}" from your inventory.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => handleDelete(product.id)}
                              className="bg-red-600 hover:bg-red-700"
                            >
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {products.length === 0 && (
                <TableRow>
                  <TableCell colSpan={7} className="text-center text-muted-foreground">
                    No products found. Add your first product to get started.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default ProductsManagement;
