// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nauojezdlsfagudtqpcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdW9qZXpkbHNmYWd1ZHRxcGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjg2NTksImV4cCI6MjA2NDk0NDY1OX0.EPMzRKK1ql34reXvoAZF49QU4FxcJOCWqnxDC83kyFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);